name: Deploy Logic App Workflow to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write  # This grants permission to request the ID token
  contents: read   # This is required for actions/checkout

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E0B1AB11D96B40CD8910EBD737FEED84 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CC473D0EB8614B81B5CB63DC9AB7F75B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2BBF50F76EC940E9A5B2998C7E36188E }}
          enable-AzPSSession: false
          auth-type: 'SERVICE_PRINCIPAL'  # Use 'sp' instead of SERVICE_PRINCIPAL for service principal authentication

      - name: Deploy Logic App Workflow
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az logic workflow deployment source config-zip \
              --resource-group test \
              --name logicapp90demo \
              --src-path ./
