name: Deploy Logic App Workflow to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Logic App Workflow
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az logic workflow deployment source config-zip \
              --resource-group test \
              --name logicapp90demo \
              --src-path ./  # Path to your workflow files
